IF OBJECT_ID(N'dbo.G_USERS', N'U') IS NOT NULL
AND COL_LENGTH(N'dbo.G_USERS', N'Email') IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_G_USERS_Email' AND object_id = OBJECT_ID(N'dbo.G_USERS'))
AND NOT EXISTS (
    SELECT Email FROM dbo.G_USERS
    WHERE Email IS NOT NULL GROUP BY Email HAVING COUNT(*) > 1)
    CREATE UNIQUE INDEX UX_G_USERS_Email ON dbo.G_USERS (Email) WHERE Email IS NOT NULL;
